wandb: logging graph, to disable use `wandb.watch(log_graph=False)`
data_cfg.trajdata_predict_types ['vehicle']
{'cache_location': '~/my_custom_cache_location', 'desired_data': ['nusc_trainval-train', 'nusc_trainval-train_val'], 'desired_dt': 0.1, 'future_sec': (5.2, 5.2), 'history_sec': (3.0, 3.0), 'data_dirs': <configs.custom_config.ConfigBase object at 0x7e43169ca5b0>, 'only_types': [<AgentType.VEHICLE: 1>], 'only_predict': [<AgentType.VEHICLE: 1>], 'agent_interaction_distances': defaultdict(<function PassUnifiedDataModule.setup.<locals>.<lambda> at 0x7e4309c95f70>, {}), 'incl_raster_map': True, 'raster_map_params': {'px_per_m': 2, 'map_size_px': 224, 'return_rgb': False, 'offset_frac_xy': [-0.5, 0.0], 'no_map_fill_value': -1.0}, 'incl_vector_map': True, 'centric': 'agent', 'scene_description_contains': None, 'standardize_data': True, 'verbose': True, 'max_agent_num': None, 'num_workers': 24, 'rebuild_cache': False, 'rebuild_maps': False, 'extras': {'closest_lane_point': <function get_closest_lane_point_wrapper.<locals>.get_closest_lane_point at 0x7e4309c95e50>, 'full_fut_traj': <function get_full_fut_traj at 0x7e42c22d11f0>, 'full_fut_valid': <function get_full_fut_valid at 0x7e42c22d1280>}}
/home/visier/ctg_project/trajdata/src/trajdata/dataset_specific/nusc/nusc_dataset.py:62: UserWarning: Beware, nusc_test has no annotations!
  warnings.warn("Beware, nusc_test has no annotations!")
Loading data for matched scene tags: ['train-nusc_trainval-boston', 'train-singapore-nusc_trainval', 'boston-train_val-nusc_trainval', 'train_val-nusc_trainval-singapore']
Calculating Agent Data (Serially): 100%|##########| 700/700 [00:00<00:00, 136915.35it/s]
700 scenes in the scene index.
Creating Agent Data Index (24 CPUs): 100%|##########| 700/700 [00:00<00:00, 17773.23it/s]
Structuring Agent Data Index: 100%|##########| 700/700 [00:00<00:00, 72616.07it/s]
Loading data for matched scene tags: ['boston-nusc_trainval-val', 'singapore-nusc_trainval-val']
Calculating Agent Data (Serially): 100%|##########| 150/150 [00:00<00:00, 122069.38it/s]
150 scenes in the scene index.
Creating Agent Data Index (24 CPUs): 100%|##########| 150/150 [00:00<00:00, 24459.44it/s]
Structuring Agent Data Index: 100%|##########| 150/150 [00:00<00:00, 60963.72it/s]
Epoch 0:  13%|#3        | 1000/7447 [03:43<24:02,  4.47it/s, v_Traceback (most recent call last):
  File "/home/visier/hazardforge/HazardForge/train.py", line 212, in <module>
    main(default_config, auto_remove_exp_dir=default_config.train.remove_exp_dir, debug=default_config.train.debug)
  File "/home/visier/hazardforge/HazardForge/train.py", line 182, in main
    trainer.fit(model=model, datamodule=datamodule)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 137, in run
    self.on_advance_end(data_fetcher)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 285, in on_advance_end
    self.val_loop.run()
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 134, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 391, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 403, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/home/visier/hazardforge/HazardForge/src/models/algos.py", line 318, in validation_step
    kl_loss, recon_loss = self(batch)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/visier/hazardforge/HazardForge/src/models/algos.py", line 222, in forward
    return super().forward(*args, **kwargs)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 668, in forward
    return super().forward(*args, **kwargs)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 244, in _forward_unimplemented
    raise NotImplementedError(f"Module [{type(self).__name__}] is missing the required \"forward\" function")
NotImplementedError: Module [UnifiedTrainer] is missing the required "forward" function
Traceback (most recent call last):
  File "/home/visier/hazardforge/HazardForge/train.py", line 212, in <module>
    main(default_config, auto_remove_exp_dir=default_config.train.remove_exp_dir, debug=default_config.train.debug)
  File "/home/visier/hazardforge/HazardForge/train.py", line 182, in main
    trainer.fit(model=model, datamodule=datamodule)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 137, in run
    self.on_advance_end(data_fetcher)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 285, in on_advance_end
    self.val_loop.run()
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 134, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 391, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 403, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/home/visier/hazardforge/HazardForge/src/models/algos.py", line 318, in validation_step
    kl_loss, recon_loss = self(batch)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/visier/hazardforge/HazardForge/src/models/algos.py", line 222, in forward
    return super().forward(*args, **kwargs)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 668, in forward
    return super().forward(*args, **kwargs)
  File "/home/visier/anaconda3/envs/hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 244, in _forward_unimplemented
    raise NotImplementedError(f"Module [{type(self).__name__}] is missing the required \"forward\" function")
NotImplementedError: Module [UnifiedTrainer] is missing the required "forward" function
